# Reading D3D grid file

In [20]:
import pandas as pd
import numpy as np
import xarray as xr

In [2]:
filename='/Users/brey/Downloads/EUR/D3D/ERAI/eur01.grd'

In [3]:
header=pd.read_csv(filename,nrows=3,header=None,comment='*')
cs = header.loc[0,0].split('=')[1].strip()
ni,nj = header.loc[1,0].split(' ')
ni,nj = int(ni),int(nj)
alfori, xori, yori = header.loc[2,0].split(' ')

In [6]:
header

0
0  Coordinate System= Spherical
1                       770 515
2                   0.0 0.0 0.0

In [9]:
d = pd.read_csv(filename,header=2,comment='*',delim_whitespace=True,engine='python',na_values='ETA=')
d = d.reset_index()
        


In [11]:
d.head()

level_0  level_1  level_2   level_3   level_4   level_5   level_6  \
0      NaN        1    -35.0 -34.89987 -34.79974 -34.69961 -34.59948   
1      NaN        2    -35.0 -34.89987 -34.79974 -34.69961 -34.59948   
2      NaN        3    -35.0 -34.89987 -34.79974 -34.69961 -34.59948   
3      NaN        4    -35.0 -34.89987 -34.79974 -34.69961 -34.59948   
4      NaN        5    -35.0 -34.89987 -34.79974 -34.69961 -34.59948   

    level_7   level_8   level_9  ...    level_762  level_763  level_764  \
0 -34.49935 -34.39922 -34.29909  ...     41.09883   41.19896   41.29909   
1 -34.49935 -34.39922 -34.29909  ...     41.09883   41.19896   41.29909   
2 -34.49935 -34.39922 -34.29909  ...     41.09883   41.19896   41.29909   
3 -34.49935 -34.39922 -34.29909  ...     41.09883   41.19896   41.29909   
4 -34.49935 -34.39922 -34.29909  ...     41.09883   41.19896   41.29909   

   level_765  level_766  level_767  level_768       0.0     0.0.1  0.0.2  
0   41.39922   41.49935   41.59948   41.69961  41.79974  41.89987   42.0  
1   41.39922   41.49935   41.59948   41.69961  41.79974  41.89987   42.0  
2   41.39922   41.49935   41.59948   41.69961  41.79974  41.89987   42.0  
3   41.39922   41.49935   41.59948   41.69961  41.79974  41.89987   42.0  
4   41.39922   41.49935   41.59948   41.69961  41.79974  41.89987   42.0  

[5 rows x 772 columns]

In [13]:
d.values

array([[         nan,   1.        , -35.        , ...,  41.79973992,
         41.89986996,  42.        ],
       [         nan,   2.        , -35.        , ...,  41.79973992,
         41.89986996,  42.        ],
       [         nan,   3.        , -35.        , ...,  41.79973992,
         41.89986996,  42.        ],
       ...,
       [         nan, 513.        ,  76.34961089, ...,  76.34961089,
         76.34961089,  76.34961089],
       [         nan, 514.        ,  76.44980545, ...,  76.44980545,
         76.44980545,  76.44980545],
       [         nan, 515.        ,  76.55      , ...,  76.55      ,
         76.55      ,  76.55      ]])

In [12]:
data = d.values[~np.isnan(d.values)]
data

array([  1.        , -35.        , -34.89986996, ...,  76.55      ,
        76.55      ,  76.55      ])

In [14]:
data=np.array(data)
data = data.reshape(2,nj,ni+1) # including the row index
#clean up the row index
data = data[:,:,1:]



In [15]:
data

array([[[-35.        , -34.89986996, -34.79973992, ...,  41.79973992,
          41.89986996,  42.        ],
        [-35.        , -34.89986996, -34.79973992, ...,  41.79973992,
          41.89986996,  42.        ],
        [-35.        , -34.89986996, -34.79973992, ...,  41.79973992,
          41.89986996,  42.        ],
        ...,
        [-35.        , -34.89986996, -34.79973992, ...,  41.79973992,
          41.89986996,  42.        ],
        [-35.        , -34.89986996, -34.79973992, ...,  41.79973992,
          41.89986996,  42.        ],
        [-35.        , -34.89986996, -34.79973992, ...,  41.79973992,
          41.89986996,  42.        ]],

       [[ 25.05      ,  25.05      ,  25.05      , ...,  25.05      ,
          25.05      ,  25.05      ],
        [ 25.15019455,  25.15019455,  25.15019455, ...,  25.15019455,
          25.15019455,  25.15019455],
        [ 25.25038911,  25.25038911,  25.25038911, ...,  25.25038911,
          25.25038911,  25.25038911],
        ...,


In [16]:
lons=data[0,:,:]
lats=data[1,:,:]      

In [17]:
lons

array([[-35.        , -34.89986996, -34.79973992, ...,  41.79973992,
         41.89986996,  42.        ],
       [-35.        , -34.89986996, -34.79973992, ...,  41.79973992,
         41.89986996,  42.        ],
       [-35.        , -34.89986996, -34.79973992, ...,  41.79973992,
         41.89986996,  42.        ],
       ...,
       [-35.        , -34.89986996, -34.79973992, ...,  41.79973992,
         41.89986996,  42.        ],
       [-35.        , -34.89986996, -34.79973992, ...,  41.79973992,
         41.89986996,  42.        ],
       [-35.        , -34.89986996, -34.79973992, ...,  41.79973992,
         41.89986996,  42.        ]])

In [18]:
lats

array([[25.05      , 25.05      , 25.05      , ..., 25.05      ,
        25.05      , 25.05      ],
       [25.15019455, 25.15019455, 25.15019455, ..., 25.15019455,
        25.15019455, 25.15019455],
       [25.25038911, 25.25038911, 25.25038911, ..., 25.25038911,
        25.25038911, 25.25038911],
       ...,
       [76.34961089, 76.34961089, 76.34961089, ..., 76.34961089,
        76.34961089, 76.34961089],
       [76.44980545, 76.44980545, 76.44980545, ..., 76.44980545,
        76.44980545, 76.44980545],
       [76.55      , 76.55      , 76.55      , ..., 76.55      ,
        76.55      , 76.55      ]])

In [21]:
g = xr.Dataset({'lons': (['y', 'x'], lons),   
                        'lats': (['y', 'x'], lats)},
                         coords={'x': ('x', lons[0,:]),   
                                 'y': ('y', lats[:,0])})         
                        
                        
g.attrs = {'Coordinate System': cs, 'alfori': alfori, 'xori': xori, 'yori': yori}




In [22]:
g

<xarray.Dataset>
Dimensions:  (x: 770, y: 515)
Coordinates:
  * y        (y) float64 25.05 25.15 25.25 25.35 25.45 25.55 25.65 25.75 ...
  * x        (x) float64 -35.0 -34.9 -34.8 -34.7 -34.6 -34.5 -34.4 -34.3 ...
Data variables:
    lons     (y, x) float64 -35.0 -34.9 -34.8 -34.7 -34.6 -34.5 -34.4 -34.3 ...
    lats     (y, x) float64 25.05 25.05 25.05 25.05 25.05 25.05 25.05 25.05 ...
Attributes:
    Coordinate System:  Spherical
    xori:               0.0
    yori:               0.0
    alfori:             0.0

In [23]:
g.lons

<xarray.DataArray 'lons' (y: 515, x: 770)>
array([[-35.     , -34.89987, -34.79974, ...,  41.79974,  41.89987,  42.     ],
       [-35.     , -34.89987, -34.79974, ...,  41.79974,  41.89987,  42.     ],
       [-35.     , -34.89987, -34.79974, ...,  41.79974,  41.89987,  42.     ],
       ...,
       [-35.     , -34.89987, -34.79974, ...,  41.79974,  41.89987,  42.     ],
       [-35.     , -34.89987, -34.79974, ...,  41.79974,  41.89987,  42.     ],
       [-35.     , -34.89987, -34.79974, ...,  41.79974,  41.89987,  42.     ]])
Coordinates:
  * y        (y) float64 25.05 25.15 25.25 25.35 25.45 25.55 25.65 25.75 ...
  * x        (x) float64 -35.0 -34.9 -34.8 -34.7 -34.6 -34.5 -34.4 -34.3 ...

In [24]:
g.lats

<xarray.DataArray 'lats' (y: 515, x: 770)>
array([[25.05    , 25.05    , 25.05    , ..., 25.05    , 25.05    , 25.05    ],
       [25.150195, 25.150195, 25.150195, ..., 25.150195, 25.150195, 25.150195],
       [25.250389, 25.250389, 25.250389, ..., 25.250389, 25.250389, 25.250389],
       ...,
       [76.349611, 76.349611, 76.349611, ..., 76.349611, 76.349611, 76.349611],
       [76.449805, 76.449805, 76.449805, ..., 76.449805, 76.449805, 76.449805],
       [76.55    , 76.55    , 76.55    , ..., 76.55    , 76.55    , 76.55    ]])
Coordinates:
  * y        (y) float64 25.05 25.15 25.25 25.35 25.45 25.55 25.65 25.75 ...
  * x        (x) float64 -35.0 -34.9 -34.8 -34.7 -34.6 -34.5 -34.4 -34.3 ...

In [25]:
g.x

<xarray.DataArray 'x' (x: 770)>
array([-35.     , -34.89987, -34.79974, ...,  41.79974,  41.89987,  42.     ])
Coordinates:
  * x        (x) float64 -35.0 -34.9 -34.8 -34.7 -34.6 -34.5 -34.4 -34.3 ...

In [26]:
g.y

<xarray.DataArray 'y' (y: 515)>
array([25.05    , 25.150195, 25.250389, ..., 76.349611, 76.449805, 76.55    ])
Coordinates:
  * y        (y) float64 25.05 25.15 25.25 25.35 25.45 25.55 25.65 25.75 ...